const express = require('express')
const morgan = require('morgan')
const router = require('./routes/router')
var app = express()
const fs = require('fs')
const requestLogger = require('./services/requestLogger')
console.log(morgan('tiny'))
app.use('/',router)
app.use('/admin',requestLogger)
app.listen(3000)
console.log("server started @3000...")